openapi: 3.0.0
info:
  title: Hobbie-Center API
  description: API to manage hobbies and users
  version: 1.0.0

paths:
  /books:
    post:
      summary: Create a new book
      description: Add a new book
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                numberOfPages:
                  type: integer
                coverUrl:
                  type: string
              required:
                - title
                - numberOfPages
                - coverUrl
      responses:
        '201':
          description: The book has been created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: book ID
        '400':
          description: Bad request
